### ISSUE TITLE
Configure gitlab widget controls hang

### ISSUE THREAD

**Issue by CodeFarmer** [junalmeida/dash-ci#32]
Browser: Google Chrome 60.0.3112.90 (Official Build) (64-bit) (cohort: Stable)
Browser: Microsoft Edge 40.15063.0.0
Browser: Chromium 60.0.3112.78 (64-bit)

OS: Windows 10 (Chrome, Edge)
OS: Sparky Linux 4 (Chromium)

The "Configure Gitlab Pipeline" and "Configure Gitlab Issues" controls both just display the spinner indefinitely. Also, on Edge, it renders with flickering scrollbars.

It's possible (really likely) that something is wrong in my configuration, but it's impossible to know what, as the application just sits there.

**Comment by junalmeida** [comment]
Hi,
This is a known issue when the provider configuration is not complete. Check the URL and token of gitlab at settings as a workaround to this issue

**Comment by junalmeida** [comment]
Closed but will be addressed at future releases.
