### ISSUE TITLE
Wildcard on references doesn't work on newer GitLab

### ISSUE THREAD

**Issue by fvicente** [junalmeida/dash-ci#45]
Thanks for this great dashboard!

It seems that with newer GitLab API (gitlab-ce 11.1.4), I cannot use * wildcard on the "ref=" parameter of the pipelines endpoint. It returns an empty array. If I leave the parameter empty it works (returns everything), however dash-ci interface somehow sets it to "master" if you try to leave Refs empty.
Could you allow the dashboard to save an empty Ref?

PS: Avatars are not displayed, however this PR fixes that problem: https://github.com/junalmeida/dash-ci/pull/43
Are you planning to merge it?

**Comment by junalmeida** [comment]
@fvicente Thank you very much for reporting it. I will take a look as soon as possible, and yes, I am planning to merge #43.

**Comment by junalmeida** [comment]
@fvicente Sorry to take long, this issue is solved :) LMK if you find anything else
